### ISSUE TITLE
Add canonical URL for custom schema vocabulary

### ISSUE THREAD

**Issue by jwijay** [stencila/schema#130]
Related to https://github.com/stencila/encoda/pull/200 and https://github.com/stencila/encoda/pull/163

We'll need to add canonical URLs (e.g. https://stencila.github.io/schema/CodeChunk.jsonld to complement existing https://stencila.github.io/schema/CodeChunk.schema.json JSON files) so we can add appropriate `itemtypes` to non-schema.org nodes.

**Comment by nokome** [comment]
@jwijay : I've started #131 for this. I'm wondering which of these might be the best option to use in `itemtypes':

- https://stencila.github.io/schema/CodeChunk.jsonld
- https://schema.stenci.la/CodeChunk 
- https://stenci.la/schema/CodeChunk 
- https://stenci.la/CodeChunk 

Some of these options would require us to enable content negotiation so that https://stenci.la/CodeChunk returns the HTML documentation but using `Accept: application/json+ld` returns the generated JSON-LD.

**Comment by jwijay** [comment]
> @jwijay : I've started #131 for this. I'm wondering which of these might be the best option to use in `itemtypes':
> 
> * https://stencila.github.io/schema/CodeChunk.jsonld
> * https://schema.stenci.la/CodeChunk
> * https://stenci.la/schema/CodeChunk
> * https://stenci.la/CodeChunk
> 
> Some of these options would require us to enable content negotiation so that https://stenci.la/CodeChunk returns the HTML documentation but using `Accept: application/json+ld` returns the generated JSON-LD.

I think the 2nd and 3rd option make the most sense, and keep things simpler. The last option seems too short, because we showcase other products, not just the schema on stenci.la (and we have subdomains/routes like https://hub.stenci.la and https://stenci.la/blog).

**Comment by nokome** [comment]
OK, let's go with https://schema.stenci.la since having a separate subdomain provides more decoupling in terms of where different things are hosted. We might be better off moving from GithubPages to Netlify to have https://schema.stenci.la/CodeChunk instead of https://schema.stenci.la/CodeChunk and enable content negotation

**Comment by alex-ketch** [comment]
I've had a positive experience with Netlify in the past 👍

**Comment by nokome** [comment]
Update:

- now building the `public` folder which includes `*.json.schema`, `*.jsonld`, `*.schema.md` (Markdown generated from schema) and `*.html`
- that folder published via Netlify to https://schema.stenci.la with rewriting e.g. https://schema.stenci.la/Article -> https://schema.stenci.la/Article.html
- all custom types and properties have a `jsonld` file e.g.
  - https://schema.stenci.la/CodeChunk.jsonld
  - https://schema.stenci.la/content.jsonld

Issues:

- Netlify is 'prettyfying' to lowercase names
- Netlify does not support content negotiation e.g. https://schema.stenci.la/CodeChunk with `Accept: application/ld+json` should redirect to https://schema.stenci.la/CodeChunk.jsonld

Regardless, I think we should go ahead and start to use `itemtype="https://schema.stenci.la/CodeChunk"` etc when encoding to HTML

**Comment by nokome** [comment]
Updates...

- Netlify still resolves to lowercase filenames:
  - e.g. https://schema.stenci.la/Cite.jsonld and https://schema.stenci.la/cite.jsonld both go to the latter
  - See https://community.netlify.com/t/my-url-paths-are-forced-into-lowercase/1659/2
  - Possible solutions:
       - use a different static site server
       - don't don't use the same case insensitive name for things
  - I'm going to look at the latter solution

- In HTML I still think we should use `itemtype="https://schema.stenci.la/CodeChunk"` (it should be a valid URL, but it doesn't need to be a particular format (it will be the HTML documentation))

- In JSON-LD files, I think we need to use "http://schema.stenci.la/v0/jsonld" in the `@context`. That's because Netlify and other do not support Content Negotiation, so we have to put the things that are usually recommended [here](https://w3c.github.io/json-ld-bp/#api-versioning) to go in the `Accept` header (content type and version) in the URL.

**Comment by nokome** [comment]
Closing this now, as URLs have been added and being used.
