### ISSUE TITLE
Consider changing Cite schema to support InlineContent

### ISSUE THREAD

**Issue by alex-ketch** [stencila/schema#133]
While working on https://github.com/stencila/encoda/issues/216 I came across some difficulties in expressing a few use cases of the `cite` tag that I encountered in the wild.

```html
<p>More information can be found in <cite>[ISO-0000]</cite>.</p>
```

```html
<footer>
  First sentence in <cite><a href="http://www.george-orwell.org/1984/0.html"><i>Nineteen Eighty-Four</i></a></cite> by George Orwell (Part 1, Chapter 1).
</footer>
```

## Proposal

- Add `content` prop constrained to `InlineContent`
- Remove the `target` prop
  - We could instead make the `target` prop optional, and then try to find if the content has a `Link` element we can find, but this sort of inter-schema property exchange seems incorrect and complicated to handle in my opinion

There was also a comment in [another Encoda PR](https://github.com/stencila/encoda/pull/200/files#diff-535ca3b825678914cb0a5a4596738f4dR69-R70) for adding `authors` and `title` props to the Cite schema.
>    * authors: (not listed in schema, but seems necessary) `ol`
>    * title: (not listed in schema, but seems necessary) `span`

However if we allow for `content` then we can use nested `Person` schema for authors, and plain string value for title.

**Comment by nokome** [comment]
The `Cite` node is currently designed to link (via the `target` property) to another `CreativeWork` in the `references` property of the current `CreativeWork`. It this way it is more similar to Pandoc's [`Citation` element](https://github.com/jgm/pandoc-types/blob/master/Text/Pandoc/Definition.hs#L277) or JATS `<xref ref-type="bibr" ...>` than to HTML `<cite>`.

Removing the `target` and adding `authors` and `title` would change `Cite` from being a reference to being a container (for the data on the other creative work). That would cause redundant information when a work is cited more than once. It would also mean that the `references` (a.k.a. bibliography) would have to be generated by iterating over the `Cite` nodes and extracting unique values. 

However, this data model does require that there be a corresponding entry in the `references` and thus makes it more complicated to allow for the simple, HTML-like citations like above. One way around this could be to change the schema for the `target` property to something like:

```yaml
  target:
    anyOf:
      - type: string
      - $ref: CreativeWork
```

That would allow both `Cite` nodes that link to a `CreativeWork` in the `references` e.g.

```yaml
type: Cite
target: ref2
```

and those that contain the `CreativeWork` that they are citing:

```yaml
type: Cite
target:
  type: Article
  title: Nineteen eighty four
  authors:
    - type: Person
      givenNames:
        - George
```

We thought about having a `content` prop but opted to try and stay as semantic as possible because the rendered content of an in-text citation is usually generated from properties of the cited work, or its position in the `references`, in ways that vary by publisher:

e.g. eLife uses authors and year

```xml
<xref ref-type="bibr" rid="bib6">Errington et al., 2014</xref>
```

e.g. F1000 uses a superscripted reference index number:

```xml
<sup><xref ref-type="bibr" rid="ref-2">2</xref></sup>
```

e.g. PLoS used a square bracketed reference index number:

```xml
[<xref ref-type="bibr" rid="pone.0178565.ref022">22</xref>]
```

Obviously when it comes to encoding as JATS we will need an option that specifies which sort of inline content to generate, and then generate it within the `Cite` node e.g. instead of the above:

```xml
<xref ref-type="bibr" rid="pone.0178565.ref022">[22]</xref>
```

For HTML, I wonder if we should generate the necessary HTML so that the theme CSS can chose how to render a `Cite` e.g.

```html
<cite><span itemprop="index">22</span><span itemprop="authors">Smith</span><span itemprop="year">1990</span></cite>
```

Regardless, we could add a `content` property to `Cite` and use that if it is defined, and generate it (on a per codec basis), if it is not.
