### ISSUE TITLE
Improve Table schema

### ISSUE THREAD

**Issue by nokome** [stencila/schema#91]
The current `Table` schema has `rows` but no equivalent of HTML's `<thead>` or `<th>`. There may be other properties, like column alignment that we _may_ want to introduce - whilst trying to remain as semantic as possible!

**Comment by alex-ketch** [comment]
MDAST assumes that [the first row of cells are the labels](https://github.com/syntax-tree/mdast#table). It may be acceptable in CSV/Markdown since most formatter specs require a header row, but I can see times where this may not be the case in more richer formats like DOCX and HTML where you can have multiple header rows and even columns.

My first thought is to add `header` boolean flag on a `tableRow` as well as on a `TableCell` schemas to allow for relatively complex tables such as the [one found here](https://www.w3.org/WAI/tutorials/tables/two-headers/#table-with-header-cells-in-the-top-row-and-first-column)


What do you think?

**Comment by nokome** [comment]
I like the idea of using a property `header`, instead of the creating a new type like table `TableHead`. You might consider using an enum instead e.g. `kind: [header, footer]`

I think we need to have a schema that could allow for irregular tables like this: https://www.w3.org/WAI/tutorials/tables/irregular/. But at the same time we don't want to have an overly complex schema. I can't help but feel that the HTML table model is overly complex with `<col>` and `<tbody>` etc. It would be good to to see if we could *represent* those more complex tables using our schema using just `TableCell`'s `kind`, `colspan`, and `rowspan` (without getting into how we would then encode those as HTML).
